// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]
use diesel::{self, prelude::*};
use rocket_contrib::database;

#[database("sqlite_database")]
pub struct DbConn(diesel::SqliteConnection);

#[derive(Queryable, Insertable)]
#[table_name = "users"]
struct User {
    ip_address: String,
    password: String,
}

#[derive(Queryable, Debug)]
pub struct Manga {
    pub id: i32,
    pub name: String,
    pub path: String,
}
