// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


#[derive(Queryable, Debug)]
pub struct Manga {
    pub id: i32,
    pub name: String,
    pub path: String,
}

#[derive(Queryable, Debug)]
pub struct User {
    pub name: String,
    pub password: String,
}

